# Project Information
site_name: TJU CIC Wiki
site_description: 北洋智算 Wiki 是由北洋智算学生自发维护的知识整合站点，帮助北洋学生提升自我，更好解决繁杂的事物。
strict: false

# Contents
nav:
  - 简介:
    - Getting Started: index.md
    - 关于本项目: intro/about.md
  - 基础课程:
    - 目录: basic/index.md

  - 计算机科学与技术:
    - 目录: cs/index.md
    - 程序设计:
      - 程序设计原理: cs/programming/cpp_programming.md
      - 程序设计实践: cs/programming/cpp_practice.md
      - 数据结构: cs/programming/data_structure.md
      - 算法设计与分析: cs/programming/algorithm.md
    - 计算机系统:
      - 计算机组成原理: cs/system/principle_of_computer_composition.md
      - 计算机系统实践: cs/system/practice_of_computer_composition.md
      - 操作系统: cs/system/os.md
      - 并行计算: cs/system/parallel_computing.md
      - 数字逻辑与数字系统: cs/system/digitial.md
      - 异构计算: cs/system/heter_computing.md
      - 计算机体系结构: cs/system/computer_architecture.md
    - 数据库:
      - 数据库原理: cs/db/db.md
      - 数据库实践: cs/db/db_practice.md
    - 计算机网络:
      - 计算机网络: cs/network/network.md
      - 计算机网络实践: cs/network/network_practice.md
    - 人工智能:
      - 人工智能基础: cs/ai/ai_basic.md
      - 自然语言处理: cs/ai/nlp.md
    - 计算机图形学: cs/graphics.md
    - 大数据分析理论与方法: cs/big_data.md

# Theme
theme:
  name: material
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  features:
    - navigation.tabs
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
