name: deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: git clone https://github.com/TJUCS/mkdocs-material --depth=1
      - run: mkdocs gh-deploy --force
